### ISSUE TITLE
Android "Could not GET highcharts-8.2.2.pom" 403 Forbidden

### ISSUE THREAD

**Issue by Benoye** [NativeScript/nativescript-ui-charts#20]
### Which platform(s) does your issue occur on?
- Android 
- Android version : 10
- OnePlus Nord N100

### Please, provide the following version numbers that your issue occurs with:

- CLI: 8.0.1
- Cross-platform modules: ?
- Runtime(s): "@nativescript/android": "^7.0.1"
- Plugin(s): "@nativescript/ui-charts": "^0.1.0"

### Please, tell us how to recreate the issue in as much detail as possible. 
When running `tns build android`, following error occurs:
```
Build file '../platforms/android/app/build.gradle' line: 633
A problem occurred configuring project ':app'.
Could not GET 'https://highsoft.bintray.com/Highcharts/com/highsoft/highcharts/highcharts/8.2.2/highcharts-8.2.2.pom'. Received status code 403 from server: Forbidden
```

**Comment by shiv19** [comment]
@Benoye 
Hey there,
are you still facing this issue?
I'm able to build it here just fine.

https://highsoft.bintray.com/Highcharts/com/highsoft/highcharts/highcharts/8.2.2/

This URL is working fine and I'm able to see the `highcharts-8.2.2.pom` file there

**Comment by Benoye** [comment]
Hi ! Sorry I forgot to update the issue
Indeed the problem was solved a few days later, I guess the dependencies was fixed on highcharts' side !
Thank you :)

**Comment by azriel46d** [comment]
Hi, this issue should be re-opened because of : https://github.com/highcharts/highcharts-android/issues/200 . As it is giving a forbidden once again

**Comment by duyendotnguyen** [comment]
I'm also still seeing the same issue  -- is there a way to download the Android highcharts `aar` locally and temporarily use it with this plugin, as suggested in the highcharts Github issue thread?
